build: false
shallow_clone: false
platform: 'x86'

install:
  - cinst git.install
  - C:\Program Files\Git\usr\bin\bash.exe -v
  - cinst virtualbox
  - set TEST_VAR=Reboot successful!
  - cinst vagrant -y --ignore-package-exit-codes --no-progress
  - ps: Restart-Computer -Force      # here the server goes restarting
  - echo before reboot
  - ps: Start-Sleep -s 10

build_script:
  - echo after reboot
  - echo %TEST_VAR%
  - cd %APPVEYOR_BUILD_FOLDER%\vagrant\ubuntu
  - vagrant up

test: off
deploy: off