build: false
shallow_clone: false
platform: 'x86'

environment:
  matrix:
  - MSYSTEM: MINGW64
    PATH: C:\msys64\usr\bin;C:\msys64\mingw64\bin;C:\Windows\System32;C:\Windows;%PATH%
  - MSYSTEM: MINGW32
    PATH: C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\Windows\System32;C:\Windows;%PATH%

install:
  #- cinst git.install
  - bash -v
  - cinst virtualbox
  - set TEST_VAR=Reboot successful!
  - cinst vagrant -y --ignore-package-exit-codes --no-progress
  - ps: Restart-Computer -Force      # here the server goes restarting
  - echo before reboot
  - ps: Start-Sleep -s 10

build_script:
  - echo after reboot
  - echo %TEST_VAR%
  - cd %APPVEYOR_BUILD_FOLDER%\vagrant\ubuntu
  - vagrant up

test: off
deploy: off