Vagrant.configure("2") do |c|

  c.vm.box = "ubuntu/trusty32"

  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.boot_timeout = 1800

  c.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    vb.customize ["modifyvm", :id, "--memory", "128"]
    vb.cpus = 1
  end

  c.vm.provision "shell", inline: <<-SHELL
     apt-get update
   SHELL
end
